[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indigo = { path = "../indigo" }
winit = "0.27.5"
pollster = "0.2.5"