[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anura = { path = "../anura" }
winit = "0.27.5"
pollster = "0.2.5"
ordered-float = "3.4.0"
env_logger = "0.10.0"